AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"

Naming/MethodParameterName:
  AllowedNames: ["iv", "b", "j", "a", "r", "t"]
  
